### ISSUE TITLE
Support RegisterCommand?

### ISSUE THREAD

**Issue by hucario** [open-unlight/node-discord-game#22]
Apologies - I don't know C so I can't really help with this, but it would be great if you could support [Discord.RegisterCommand](https://discord.com/developers/docs/game-sdk/activities#registercommand)

**Comment by elct9620** [comment]
Our application didn't need this feature, so it doesn't support it for now.

**Comment by hucario** [comment]
Yeah, fair enough

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by elct9620** [comment]
I will close this issue if you have any idea or suggestion for this feature, you can reopen it.
