### ISSUE TITLE
Assertion failed: ... file discord_game.c, line 57.

### ISSUE THREAD

**Issue by CodyRWhite** [open-unlight/node-discord-game#29]
Hello I am having issues running this app. I am able to get my electron app to load and display but as soon as I run the function to Discord.Create() I run into an Assertion Failed. 

What am I missing/doing wrong. 

```
Assertion failed: (napi_get_value_bool(env, argv[1], &is_required) == napi_ok), function Create, file discord_game.c, line 57.
/Users/codywhite/Documents/GitHub/Playstation-Discord2/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGABRT
error Command failed with exit code 1.
```

Thanks. 

## Build Info

NodeJS Version: v16.6.0
npm@7.19.1
yarn version v1.22.10

```
info Direct dependencies
├─ cross-env@7.0.3
├─ discord-game@0.1.2
├─ electron-builder@22.11.7
├─ electron-icon-maker@0.0.5
├─ electron-log@4.4.1
├─ electron-packager@15.3.0
├─ electron-store@8.0.0
├─ electron-updater@4.3.9
├─ electron@13.1.7
├─ eslint@7.32.0
├─ register-scheme@0.0.2
├─ sass@1.37.1
└─ typescript@4.3.5
```

**Comment by elct9620** [comment]
Do you provide the `client id` when calling `Discord.Create()`?

**Comment by CodyRWhite** [comment]
Client ID = Discord Application ID correct ? 

Then Yes.

**Comment by elct9620** [comment]
The second argument is provided or not?

**Comment by CodyRWhite** [comment]
Discord.create('Client ID', "xxxxxx");

Where xxxx = my discord application ID.

**Comment by CodyRWhite** [comment]
wow fail.. 

I figured it out.
