### ISSUE TITLE
Any way send scope for oauth2 token

### ISSUE THREAD

**Issue by serkandyck** [open-unlight/node-discord-game#5]
Hello thnx forawesome library, i dont understand c++ code but, anyway we can using scope? default only get identify scope i'm need guilds scope too ?

**Comment by elct9620** [comment]
This is "Discord Game SDK" for add Discord Game related features to your game. (eg. achievement, the voice in the game)
You can reference the document at [here](https://discord.com/developers/docs/game-sdk/sdk-starter-guide)

If you need `guilds` scope, you have to use other packages (eg. [discord.js](https://discord.js.org/#/)), they are different API for the different use case.
