### ISSUE TITLE
discord_game.node is not a valid Win32 application

### ISSUE THREAD

**Issue by lilabyte** [open-unlight/node-discord-game#6]
node_modules\discord-game\build\Release\discord_game.node is not a valid Win32 application.

OS: Windows 10 x64
Electron: 8.2.0
Node: 12.6.3

**Comment by elct9620** [comment]
Can you describe the previous steps before you get this message?

**Comment by lilabyte** [comment]
Yes sir

`npm i discord-game`
Moved discord_game_sdk.dll to the main directory
```
const Discord = require('discord-game')
Discord.create('Client ID', true);

Discord.Application
       .getOAuth2Token()
       .then(function(token) { console.log('Token is', token) });
```

and `npm start`

**Comment by elct9620** [comment]
Do you put the `discord_game.dll` to the application root?

You can reference [this discussion](https://github.com/open-unlight/node-discord-game/issues/4#issuecomment-622264100), the [README](https://github.com/open-unlight/node-discord-game#windows-setup) is noted it.

**Comment by lilabyte** [comment]
![image](https://user-images.githubusercontent.com/38222444/82301393-7b4e9080-99b8-11ea-91db-70ca56cadb5f.png)
yes sir

**Comment by elct9620** [comment]
Can you check your Node.js is Win32 or Win64, I find the Stackoverflow has an [answer](https://stackoverflow.com/questions/13035760/node-js-native-module-is-not-a-valid-win32-application-error) points out the problem may caused by Node.js binary.

**Comment by lilabyte** [comment]
My node.js is Win64

**Comment by lilabyte** [comment]
No idea why but somehow github downloads empty .dll files for me. When i downloaded this by view raw all works.
