### ISSUE TITLE
Problem with deauthorization

### ISSUE THREAD

**Issue by lilabyte** [open-unlight/node-discord-game#7]
When someone will authorize  appliaction using the Discord.Application.getOauth2Token(); and after that if he will deauthorize appliaction when I use Discord.Appliaction.getOauth2Token(); i have no Promise and i can't try to authorize him another time. He must restart the app.

**Comment by elct9620** [comment]
The Discord Game SDK didn't provide deauthorize API, if you find it in the document you can tell us.
