### ISSUE TITLE
Activity timestamp 

### ISSUE THREAD

**Issue by lilabyte** [open-unlight/node-discord-game#8]
I've just started the app with this:
```javascript
var activity = {
    details: "Snity Main Launcher",
    state: `${config.account_status}`,
    assets: {
        largeImage: 'snity-wbg2',
        largeText: 'Snity.net',
        smallImage: 'pineapple',
        smallText: 'Pineapple'
    },
    timestamps: {
        startAt: new Date()
    }
}
///////////////////////
activity.timestamps.startAt = new Date()
Discord.Activity
    .update(activity)
    .then(function() { console.log('Rich Presence updated') });
```
And that's what i got 
![image](https://user-images.githubusercontent.com/38222444/82727977-23809400-9cee-11ea-9371-5c6615d9a7a1.png)
The app was running less than 10 seconds

**Comment by elct9620** [comment]
![截圖 2020-09-01 下午5 46 54](https://user-images.githubusercontent.com/887984/91835001-60f4a600-ec7b-11ea-89f4-e1bfb54664d5.png)

I had updated the package, it seems works well for now. If you still have the same problem with it, please reopen this issue.
